###1 Скачайте файл с предложениями (sentences.txt).


In [101]:
import numpy as np
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


###2 Каждая строка в файле соответствует одному предложению. Считайте их, приведите каждую к нижнему регистру с помощью строковой функции lower().

###3 Произведите токенизацию, то есть разбиение текстов на слова. Для этого можно воспользоваться регулярным выражением, которое считает разделителем любой символ, не являющийся буквой: re.split('[^a-z]', t). Не забудьте удалить пустые слова после разделения.

###4 Составьте список всех слов, встречающихся в предложениях. Сопоставьте каждому слову индекс от нуля до (d - 1), где d — число различных слов в предложениях. Для этого удобно воспользоваться структурой dict.

In [102]:
handle = open('/content/drive/My Drive/Colab_Notebooks/sentences.txt')
file_object = open('/content/drive/My Drive/Colab_Notebooks/submission-1.txt', 'w')

In [103]:
import re
handle = open('/content/drive/My Drive/Colab_Notebooks/sentences.txt')
i = 0
lst = list()
new_line = list()
uniq_word = dict()
data = (handle.readlines())
for line in data: 
  line = line.strip().lower() 
  line = re.split('[^a-z]', line) #tokenization
  new_line = [x for x in line if x != ''] #drop empty words
  lst.append(new_line)
  for words in new_line:
    if words not in uniq_word:
      uniq_word[words] = i #numeric words in the dictinary
      i += 1
print('Text entoire = ', lst)
print('Uniq words =', uniq_word)



Text entoire =  [['in', 'comparison', 'to', 'dogs', 'cats', 'have', 'not', 'undergone', 'major', 'changes', 'during', 'the', 'domestication', 'process'], ['as', 'cat', 'simply', 'catenates', 'streams', 'of', 'bytes', 'it', 'can', 'be', 'also', 'used', 'to', 'concatenate', 'binary', 'files', 'where', 'it', 'will', 'just', 'concatenate', 'sequence', 'of', 'bytes'], ['a', 'common', 'interactive', 'use', 'of', 'cat', 'for', 'a', 'single', 'file', 'is', 'to', 'output', 'the', 'content', 'of', 'a', 'file', 'to', 'standard', 'output'], ['cats', 'can', 'hear', 'sounds', 'too', 'faint', 'or', 'too', 'high', 'in', 'frequency', 'for', 'human', 'ears', 'such', 'as', 'those', 'made', 'by', 'mice', 'and', 'other', 'small', 'animals'], ['in', 'one', 'people', 'deliberately', 'tamed', 'cats', 'in', 'a', 'process', 'of', 'artificial', 'selection', 'as', 'they', 'were', 'useful', 'predators', 'of', 'vermin'], ['the', 'domesticated', 'cat', 'and', 'its', 'closest', 'wild', 'ancestor', 'are', 'both', 'dip

###5 Создайте матрицу размера n * d, где n — число предложений. Заполните ее: элемент с индексом (i, j) в этой матрице должен быть равен количеству вхождений j-го слова в i-е предложение. У вас должна получиться матрица размера 22 * 254.

In [104]:
main_matrix = np.zeros((d, len(uniq_word))) #create matrix with zeros
main_matrix.shape

(22, 254)

In [105]:
for z in range(len(lst)): # Fill the matrix
    for x in lst[z]:
        main_matrix[z][uniq_word[x]] += 1
print(main_matrix)

[[1. 1. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 2. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 1. 1. 1.]]


###6 Найдите косинусное расстояние от предложения в самой первой строке (In comparison to dogs, cats have not undergone...) до всех остальных с помощью функции scipy.spatial.distance.cosine. Какие номера у двух предложений, ближайших к нему по этому расстоянию (строки нумеруются с нуля)? Эти два числа и будут ответами на задание. Само предложение (In comparison to dogs, cats have not undergone... ) имеет индекс 0.

In [108]:
first_sent = np.array(main_matrix[0, :])
row = 2
distance = 0
min_dist = dict()
while row < int(main_matrix.shape[0]):
  compair_sent = np.array(main_matrix[row, :])
  distance = dist.cosine(first_sent, compair_sent) #cosinus between first sentence and others in the matrix
  min_dist[row] = distance
  row += 1
m = 1
sequence = []
for key in min_dist: #sorting
  if min_dist[key] < m:
    m = min_dist[key]
    sequence.append(key)
result = f'{sequence[-1]} {sequence[-2]}' #convert to string
result

'6 4'

###7 Запишите полученные числа в файл, разделив пробелом. Обратите внимание, что файл должен состоять из одной строки, в конце которой не должно быть переноса. Пример файла с решением вы можете найти в конце задания (submission-1.txt).

In [107]:
file_object.write(result)
file_object.close()
handle.close()

###8 Совпадают ли ближайшие два предложения по тематике с первым? Совпадают ли тематики у следующих по близости предложений?